name = "{{replace: name}}"
main = "src/index.ts"
compatibility_date = "2023-10-23"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "wake-on-lan"
database_id = "{{replace: databse_id}}"
